openapi: 3.0.3
info:
  title: BFPortal API
  version: 1.0.0
  description: Get portal experiences from outside the website
paths:
  /admin/api/main/documents/:
    get:
      operationId: admin_api_main_documents_retrieve
      tags:
      - admin
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /admin/api/main/documents/{id}/:
    get:
      operationId: admin_api_main_documents_retrieve_2
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - admin
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /admin/api/main/documents/find/:
    get:
      operationId: admin_api_main_documents_find_retrieve
      tags:
      - admin
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /admin/api/main/images/:
    get:
      operationId: admin_api_main_images_retrieve
      tags:
      - admin
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /admin/api/main/images/{id}/:
    get:
      operationId: admin_api_main_images_retrieve_2
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - admin
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /admin/api/main/images/find/:
    get:
      operationId: admin_api_main_images_find_retrieve
      tags:
      - admin
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /admin/api/main/pages/:
    get:
      operationId: admin_api_main_pages_retrieve
      tags:
      - admin
      security:
      - cookieAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /admin/api/main/pages/{id}/:
    get:
      operationId: admin_api_main_pages_retrieve_2
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - admin
      security:
      - cookieAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /admin/api/main/pages/{id}/action/{action_name}/:
    post:
      operationId: admin_api_main_pages_action_create
      parameters:
      - in: path
        name: action_name
        schema:
          type: string
        required: true
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - admin
      security:
      - cookieAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /admin/api/main/pages/find/:
    get:
      operationId: admin_api_main_pages_find_retrieve
      tags:
      - admin
      security:
      - cookieAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/experiences/:
    get:
      operationId: api_experiences_retrieve
      description: |-
        ViewSet used to define how the api for ExperiencePage will work.

        # todo: serialize all field
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/experiences/{id}/:
    get:
      operationId: api_experiences_retrieve_2
      description: |-
        ViewSet used to define how the api for ExperiencePage will work.

        # todo: serialize all field
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/experiences/find/:
    get:
      operationId: api_experiences_find_retrieve
      description: |-
        ViewSet used to define how the api for ExperiencePage will work.

        # todo: serialize all field
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/schema/:
    get:
      operationId: api_schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /api/users/:
    get:
      operationId: api_users_retrieve
      description: ViewSet used to define how the api for ExperiencePage will work.
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/users/{id}/:
    get:
      operationId: api_users_retrieve_2
      description: ViewSet used to define how the api for ExperiencePage will work.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/users/find/:
    get:
      operationId: api_users_find_retrieve
      description: ViewSet used to define how the api for ExperiencePage will work.
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
servers:
- http://bfportal.gg/api
